const data = {
  products: [
    {
      id: "1",
      name: "CR90 Corvette",
      price: 3500000,
      model_name: "CR90 Corvette",
      isAvailable: true,
      price_type: "$",
    },
    {
      id: "2",
      name: "Star Destroyer",
      price: 150000000,
      model_name: "Imperial I-class Star Destroyer",
      isAvailable: true,
      price_type: "$",
    },
    {
      id: "3",
      name: "Sentinel-class landing craft",
      price: 240000,
      model_name: "Sentinel-class landing craft",
      isAvailable: true,
      price_type: "$",
    },
    {
      id: "4",
      name: "Death Star",
      price: 1000000000000,
      model_name: "DS-1 Orbital Battle Station",
      isAvailable: true,
      price_type: "$",
    },
    {
      id: "5",
      name: "Millenium Falcon",
      price: 134999,
      model_name: "YT-1300 light freighter",
      isAvailable: true,
      price_type: "$",
    },
    {
      id: "6",
      name: "Y-wing",
      price: 3500000,
      model_name: "BTL Y-wing",
      isAvailable: true,
      price_type: "$",
    },
    {
      id: "7",
      name: "X-wing",
      price: 149999,
      model_name: "T-65 X-wing",
      isAvailable: true,
      price_type: "$",
    },
    {
      id: "8",
      name: "TIE Advanced x1",
      price: 100,
      model_name: "Twin Ion Engine Advanced x1",
      isAvailable: false,
      price_type: "$",
    },
    {
      id: "9",
      name: "Executor",
      price: 1143350000,
      model_name: "Executor-class star dreadnought",
      isAvailable: true,
      price_type: "$",
    },
    {
      id: "10",
      name: "Rebel Transport",
      price: 3500000,
      model_name: "GR-75 medium Transport",
      isAvailable: false,
      price_type: "$",
    },
  ],
};

export default data;
